name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the environment
        run: |
          echo "Setting up the environment..."
      
      - name: Extract issue details
        id: extract_details
        run: |
          echo "issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "issue_body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "issue_url=$(jq -r '.issue.html_url' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "Issue Title: $issue_title"
          echo "Issue Body: $issue_body"
          echo "Issue URL: $issue_url"

      - name: Create Jira issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
          ISSUE_TITLE: ${{ env.issue_title }}
          ISSUE_BODY: ${{ env.issue_body }}
          ISSUE_URL: ${{ env.issue_url }}
        run: |
          json_payload=$(jq -n \
            --arg project "$JIRA_PROJECT_KEY" \
            --arg summary "$ISSUE_TITLE" \
            --arg description "$ISSUE_BODY\n\nGitHub Issue URL: $ISSUE_URL" \
            --arg issuetype "Task" \
            --arg epic_link "$JIRA_EPIC_KEY" \
            '{
              fields: {
                project: { key: $project },
                summary: $summary,
                description: $description,
                issuetype: { name: $issuetype },
                customfield_10008: $epic_link
              }
            }')

          echo "JSON Payload: $json_payload"

          curl -X POST \
            -H "Authorization: Basic $(echo -n $JIRA_EMAIL:$JIRA_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            --data "$json_payload" \
            $JIRA_BASE_URL/rest/api/2/issue/
