name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira issue
        env:
          JIRA_BASE_URL: "https://ucldata.atlassian.net"
          JIRA_EMAIL: "ccaechu@ucl.ac.uk" # Replace with your actual Jira email
          JIRA_API_TOKEN: "ATATT3xFfGF0UbGrCQ9Lza_4wn2yL5QIPl4sTmcuAvqZWSgdarzsxnP9ggwaUJ9y-TJzUgojLSrdebQ--2LrKyKaMSVvLIDO6xC_MuIh1ieOiXtYp12TXF0KFHN0OsH2pZHsb0vbE1pOFTkwzO-rvsr0AWXJ-nw88JiDPtLQJ9DPtQ1CMFmiehI=A3E25173" # Replace with your actual Jira API token
          JIRA_PROJECT_KEY: "AC"
          JIRA_EPIC_KEY: "AC-587"
        run: |
          issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          issue_body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
          issue_url=$(jq -r '.issue.html_url' "$GITHUB_EVENT_PATH")

          echo "Issue Title: $issue_title"
          echo "Issue Body: $issue_body"
          echo "Issue URL: $issue_url"

          json_payload=$(jq -n \
            --arg project "$JIRA_PROJECT_KEY" \
            --arg summary "$issue_title" \
            --arg description "$issue_body\n\nGitHub Issue URL: $issue_url" \
            --arg issuetype "Task" \
            --arg epic_link "$JIRA_EPIC_KEY" \
            '{
              fields: {
                project: { key: $project },
                summary: $summary,
                description: $description,
                issuetype: { name: $issuetype },
                customfield_10008: $epic_link
              }
            }')

          echo "JSON Payload: $json_payload"

          curl -X POST \
            -H "Authorization: Basic $(echo -n $JIRA_EMAIL:$JIRA_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            --data "$json_payload" \
            $JIRA_BASE_URL/rest/api/2/issue/
