name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          JIRA_EPIC_KEY: ${{ secrets.JIRA_EPIC_KEY }}
        run: |
          issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          issue_body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
          issue_url=$(jq -r '.issue.html_url' "$GITHUB_EVENT_PATH")

          curl -X POST \
            -H "Authorization: Basic $(echo -n $JIRA_EMAIL:$JIRA_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            --data '{
              "fields": {
                "project": {
                  "key": "'$JIRA_PROJECT_KEY'"
                },
                "summary": "'$issue_title'",
                "description": "'$issue_body\n\nGitHub Issue URL: $issue_url'",
                "issuetype": {
                  "name": "Task"
                },
                "customfield_10008": "'$JIRA_EPIC_KEY'"
              }
            }' \
            $JIRA_BASE_URL/rest/api/2/issue/
